---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
node: true

extends:
- 'airbnb-base'

rules:
no-console: 0
import/extensions: 0

# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 2020
